#!/bin/sh
#
#	A collection of aliases that I use on a regular basis.
#

# open config file in editor
alias zconfig="$EDITOR $HOME/.zshrc"
alias bconfig="$EDITOR $HOME/.bashrc"

# manage dotfiles using the config alias
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

# remap 'ls' to colorize then add some convenience aliases
alias ls="ls -G"
alias ll="ls -lFh"
alias la="ls -lFhd .*"

# sso and vscode helper aliases
alias sso=/Applications/aws-sso-helper.app/Contents/MacOS/aws-sso-helper
alias code='/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron'

# maven related aliases
alias mci="mvn clean install"
alias mca="mvn clean install -Pall"
alias mcr="mvn clean install -DskipTests -Dcheckstyle.skip -Dspotbugs.skip"

# curl alias that includes timing information
alias tcurl="curl -sw \"
   namelookup:  %{time_namelookup}s\n\
      connect:  %{time_connect}s\n\
   appconnect:  %{time_appconnect}s\n\
  pretransfer:  %{time_pretransfer}s\n\
     redirect:  %{time_redirect}s\n\
starttransfer:  %{time_starttransfer}s\n\
-------------------------\n\
        total:  %{time_total}s\n\""

alias kwhoami="kctx"
alias awswhoami="aws sts get-caller-identity"

# general navigation
#alias dev="cd /Users/christopher.allen/Development/src/github.com/ironnetcybersecurity"
