#!/bin/sh

#
# Following the methodology described here: https://antelo.medium.com/how-to-manage-your-dotfiles-with-git-f7aeed8adf8b
#

# On new machines simply do the following (as easy as 123): 
#   1. git clone --bare https://github.com/USERNAME/dotfiles.git $HOME/.dotfiles
#   2. /usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME checkout
#   3. dotfiles config --local status.showUntrackedFiles no
# Once everything is checked out, the dotfiles function will be available and should be used when updating scripts
dotfiles () {
    git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME $@
}
