#!/bin/sh

nvm () {
	if ! command -v "$nvm" > /dev/null; then
		echo "🚨 NVM not loaded! Loading now..."
		[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
    	[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && . "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
	fi
	nvm "$@"
}
